services:
  postgresdb:
    image: 'postgres:13.1-alpine'
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=resource_db
    volumes:
      - db:/var/lib/postgres
  app:
    depends_on:
      - postgresdb
    build:
      context: .
    container_name: resource_service
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresdb:5432/resource_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db: