services:
#  postgresdb:
#    image: 'postgres:13.1-alpine'
#    restart: unless-stopped
#    ports:
#      - "5433:5432"
#    expose:
#      - "5432"
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=resource_db
#    volumes:
#      - db:/var/lib/postgres
#  app:
#    depends_on:
#      - postgresdb
#    build:
#      context: .
#    restart: unless-stopped
#    ports:
      - "8080:8081"
#    expose:
      - "8080"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresdb:5432/resource_db
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=postgres
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update